apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecowalk-cluster
  region: us-east-1 # Bạn có thể đổi sang ap-southeast-1 (Singapore) nếu muốn gần VN hơn
  version: "1.31"

# Quản lý các máy chủ (Nodes)
managedNodeGroups:
  - name: ecowalk-nodes
    instanceType: t3.medium # RAM 4GB, CPU 2 Core - Phù hợp chạy Backend
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true # Cho phép SSH vào node để debug nếu cần
    labels:
      role: worker
    tags:
      nodegroup-role: worker

# Kích hoạt quyền truy cập IAM cho các Service Account (Rất quan trọng cho Backend)
iam:
  withOIDC: true
