spring.application.name=demo

# PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-cold-bar-adey6gmg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WYQjr8mewcO9
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8081

# JWT
app.jwt.secret=RANDOM_SECRET_KEY_CHANGE_THIS_1234567890_!@#
app.jwt.access-exp-ms=900000
app.jwt.refresh-exp-ms=604800000  

# CORS
app.cors.allowed-origins=http://localhost:3000 

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Firebase Configuration
firebase.credentials.path=service-account.json

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
