spring.application.name=demo

# Cấu hình kết nối PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-aged-glitter-ad5qlgw2-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MlhHxAOB9D0p
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình cổng chạy ứng dụng
server.port=8080