spring.application.name=demo

# Cấu hình kết nối PostgreSQL Neon
spring.datasource.url=jdbc:postgresql://ep-cold-bar-adey6gmg-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WYQjr8mewcO9
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình cổng chạy ứng dụng
server.port=8080

# JWT
app.jwt.secret=RANDOM_SECRET_KEY_CHANGE_THIS_1234567890_!@#
# Thời gian sống access token (ms)
# 15 phút = 15 * 60 * 1000 = 900000
app.jwt.access-exp-ms=900000

# Thời gian sống refresh token (ms)
# 7 ngày = 7 * 24 * 60 * 60 * 1000 = 604800000
app.jwt.refresh-exp-ms=604800000  

# CORS (ví dụ)
app.cors.allowed-origins=http://localhost:3000 

# đổi port nếu frontend chạy ở port khác 